# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: openjdk:12-jdk
      environment:
        # PG client params (test conf fetch them from env)
        TEST_PGUSER: signalconso
        TEST_PGHOST: localhost
        TEST_PGDATABASE: test_signalconso
        # Customize the JVM maximum heap limit
        JVM_OPTS: -Xmx3200m
        TERM: dumb

    # See https://circleci.com/docs/2.0/postgres-config/
    - image: circleci/postgres:10.6-ram
      environment:
        POSTGRES_USER: signalconso
        POSTGRES_DB: test_signalconso

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v2-dependencies--{{ checksum "build.sbt" }}
        # fallback to using the latest cache if no exact match is found
        - v2-dependencies--

    - run: cat /dev/null | sbt test:compile

    - save_cache:
        paths:
        - ~/.ivy2
        - ~/.m2
        - ~/.sbt
        - target/resolution-cache
        - target/streams
        - project/target/resolution-cache
        - project/target/streams
        key: v2-dependencies--{{ checksum "build.sbt" }}

    # run tests!
    - run: cat /dev/null | sbt test
